2020-10-28 21:11:54,748 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-30 10:57:47,584 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-30 10:58:41,923 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-30 11:06:28,865 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-30 11:07:26,874 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-30 14:41:49,802 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-30 14:42:12,796 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-30 14:59:37,061 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-30 15:00:09,470 ERROR: Exception on /user/susan [GET] [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/routes.py", line 55, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-10-30 15:00:12,012 ERROR: Exception on /user/susan [GET] [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/routes.py", line 55, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-10-30 15:01:01,164 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-31 13:42:09,695 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-31 13:43:37,150 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-31 13:43:52,983 ERROR: Exception on /index [GET] [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/routes.py", line 13, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-10-31 13:44:32,416 INFO: My flask startup [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/__init__.py:31]
2020-10-31 13:44:33,376 ERROR: Exception on /index [GET] [in /mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/routes.py", line 21, in index
    return render_template('index.html', title='Home', posts=posts, form=form)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/obama/Desktop/Py-WebCS50/Flask/myflasky/app/templates/index.html", line 16, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
